# Generated by Django 5.1.3 on 2024-11-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_fan', models.IntegerField(default=0)),
                ('table', models.IntegerField(default=0)),
                ('chair', models.IntegerField(default=0)),
                ('refrigerator', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LatestCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=None)),
                ('father_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rooms', models.IntegerField(default=None)),
                ('occupied', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=None)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('hostel_number', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to='admin_app.studentdetailmodel')),
            ],
        ),
    ]
