# Generated by Django 5.1.3 on 2024-11-28 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
