# Generated by Django 5.1.3 on 2024-11-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_studentrecord_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='total_duration',
        ),
    ]
