# Generated by Django 5.1.3 on 2024-11-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_studentrecord_total_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_fan', models.IntegerField(default=0)),
                ('table', models.IntegerField(default=0)),
                ('chair', models.IntegerField(default=0)),
                ('refrigerator', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rooms', models.IntegerField(default=None)),
                ('occupied', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=None)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.furniture')),
            ],
        ),
    ]
