# Generated by Django 5.1.3 on 2024-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_furniture_hostelview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelview',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
